#!/bin/sh
# Get and format HTML of each item's page
curl https://minecraft.fandom.com/wiki/Item  > wiki/Item.html
curl https://minecraft.fandom.com/wiki/Item  > wiki/Item.html
curl https://minecraft.fandom.com/wiki/Amethyst_Shard  > wiki/Amethyst_Shard.html
curl https://minecraft.fandom.com/wiki/Blaze_Rod  > wiki/Blaze_Rod.html
curl https://minecraft.fandom.com/wiki/Bone  > wiki/Bone.html
curl https://minecraft.fandom.com/wiki/Clay_Ball  > wiki/Clay_Ball.html
curl https://minecraft.fandom.com/wiki/Coal  > wiki/Coal.html
curl https://minecraft.fandom.com/wiki/Diamond  > wiki/Diamond.html
curl https://minecraft.fandom.com/wiki/Disc_Fragment_5  > wiki/Disc_Fragment_5.html
curl https://minecraft.fandom.com/wiki/Dragon%27s_Breath  > wiki/Dragon%27s_Breath.html
curl https://minecraft.fandom.com/wiki/Echo_Shard  > wiki/Echo_Shard.html
curl https://minecraft.fandom.com/wiki/Emerald  > wiki/Emerald.html
curl https://minecraft.fandom.com/wiki/Ender_Pearl  > wiki/Ender_Pearl.html
curl https://minecraft.fandom.com/wiki/Feather  > wiki/Feather.html
curl https://minecraft.fandom.com/wiki/Flint  > wiki/Flint.html
curl https://minecraft.fandom.com/wiki/Ghast_Tear  > wiki/Ghast_Tear.html
curl https://minecraft.fandom.com/wiki/Glowstone_Dust  > wiki/Glowstone_Dust.html
curl https://minecraft.fandom.com/wiki/Gunpowder  > wiki/Gunpowder.html
curl https://minecraft.fandom.com/wiki/Heart_of_the_Sea  > wiki/Heart_of_the_Sea.html
curl https://minecraft.fandom.com/wiki/Honeycomb  > wiki/Honeycomb.html
curl https://minecraft.fandom.com/wiki/Ink_Sac  > wiki/Ink_Sac.html
curl https://minecraft.fandom.com/wiki/Glow_Ink_Sac  > wiki/Glow_Ink_Sac.html
curl https://minecraft.fandom.com/wiki/Lapis_Lazuli  > wiki/Lapis_Lazuli.html
curl https://minecraft.fandom.com/wiki/Leather  > wiki/Leather.html
curl https://minecraft.fandom.com/wiki/Magma_Cream  > wiki/Magma_Cream.html
curl https://minecraft.fandom.com/wiki/Nautilus_Shell  > wiki/Nautilus_Shell.html
curl https://minecraft.fandom.com/wiki/Nether_Quartz  > wiki/Nether_Quartz.html
curl https://minecraft.fandom.com/wiki/Nether_Star  > wiki/Nether_Star.html
curl https://minecraft.fandom.com/wiki/Nether_Wart  > wiki/Nether_Wart.html
curl https://minecraft.fandom.com/wiki/Phantom_Membrane  > wiki/Phantom_Membrane.html
curl https://minecraft.fandom.com/wiki/Prismarine_Shard  > wiki/Prismarine_Shard.html
curl https://minecraft.fandom.com/wiki/Prismarine_Crystals  > wiki/Prismarine_Crystals.html
curl https://minecraft.fandom.com/wiki/Rabbit_Hide  > wiki/Rabbit_Hide.html
curl https://minecraft.fandom.com/wiki/Rabbit%27s_Foot  > wiki/Rabbit%27s_Foot.html
curl https://minecraft.fandom.com/wiki/Raw_Copper  > wiki/Raw_Copper.html
curl https://minecraft.fandom.com/wiki/Raw_Gold  > wiki/Raw_Gold.html
curl https://minecraft.fandom.com/wiki/Raw_Iron  > wiki/Raw_Iron.html
curl https://minecraft.fandom.com/wiki/Redstone_Dust  > wiki/Redstone_Dust.html
curl https://minecraft.fandom.com/wiki/Scute  > wiki/Scute.html
curl https://minecraft.fandom.com/wiki/Shulker_Shell  > wiki/Shulker_Shell.html
curl https://minecraft.fandom.com/wiki/Slimeball  > wiki/Slimeball.html
curl https://minecraft.fandom.com/wiki/Stick  > wiki/Stick.html
curl https://minecraft.fandom.com/wiki/String  > wiki/String.html
curl https://minecraft.fandom.com/wiki/Wheat  > wiki/Wheat.html
curl https://minecraft.fandom.com/wiki/Blaze_Powder  > wiki/Blaze_Powder.html
curl https://minecraft.fandom.com/wiki/Book  > wiki/Book.html
curl https://minecraft.fandom.com/wiki/Brick  > wiki/Brick.html
curl https://minecraft.fandom.com/wiki/Nether_Brick  > wiki/Nether_Brick.html
curl https://minecraft.fandom.com/wiki/Charcoal  > wiki/Charcoal.html
curl https://minecraft.fandom.com/wiki/Copper_Ingot  > wiki/Copper_Ingot.html
curl https://minecraft.fandom.com/wiki/Fermented_Spider_Eye  > wiki/Fermented_Spider_Eye.html
curl https://minecraft.fandom.com/wiki/Firework_Star  > wiki/Firework_Star.html
curl https://minecraft.fandom.com/wiki/Glistering_Melon_Slice  > wiki/Glistering_Melon_Slice.html
curl https://minecraft.fandom.com/wiki/Gold_Ingot  > wiki/Gold_Ingot.html
curl https://minecraft.fandom.com/wiki/Gold_Nugget  > wiki/Gold_Nugget.html
curl https://minecraft.fandom.com/wiki/Iron_Ingot  > wiki/Iron_Ingot.html
curl https://minecraft.fandom.com/wiki/Iron_Nugget  > wiki/Iron_Nugget.html
curl https://minecraft.fandom.com/wiki/Netherite_Ingot  > wiki/Netherite_Ingot.html
curl https://minecraft.fandom.com/wiki/Netherite_Scrap  > wiki/Netherite_Scrap.html
curl https://minecraft.fandom.com/wiki/Paper  > wiki/Paper.html
curl https://minecraft.fandom.com/wiki/Popped_Chorus_Fruit  > wiki/Popped_Chorus_Fruit.html
curl https://minecraft.fandom.com/wiki/Sugar  > wiki/Sugar.html
curl https://minecraft.fandom.com/wiki/BE  > wiki/BE.html
curl https://minecraft.fandom.com/wiki/EE  > wiki/EE.html
curl https://minecraft.fandom.com/wiki/Bleach  > wiki/Bleach.html
curl https://minecraft.fandom.com/wiki/Compound  > wiki/Compound.html
curl https://minecraft.fandom.com/wiki/Beetroot_Seeds  > wiki/Beetroot_Seeds.html
curl https://minecraft.fandom.com/wiki/Cocoa_Beans  > wiki/Cocoa_Beans.html
curl https://minecraft.fandom.com/wiki/Melon_Seeds  > wiki/Melon_Seeds.html
curl https://minecraft.fandom.com/wiki/Pumpkin_Seeds  > wiki/Pumpkin_Seeds.html
curl https://minecraft.fandom.com/wiki/Wheat_Seeds  > wiki/Wheat_Seeds.html
curl https://minecraft.fandom.com/wiki/Food  > wiki/Food.html
curl https://minecraft.fandom.com/wiki/Apple  > wiki/Apple.html
curl https://minecraft.fandom.com/wiki/Golden_Apple  > wiki/Golden_Apple.html
curl https://minecraft.fandom.com/wiki/Enchanted_Golden_Apple  > wiki/Enchanted_Golden_Apple.html
curl https://minecraft.fandom.com/wiki/Beetroot  > wiki/Beetroot.html
curl https://minecraft.fandom.com/wiki/Bread  > wiki/Bread.html
curl https://minecraft.fandom.com/wiki/Carrot  > wiki/Carrot.html
curl https://minecraft.fandom.com/wiki/Golden_Carrot  > wiki/Golden_Carrot.html
curl https://minecraft.fandom.com/wiki/Chorus_Fruit  > wiki/Chorus_Fruit.html
curl https://minecraft.fandom.com/wiki/Cookie  > wiki/Cookie.html
curl https://minecraft.fandom.com/wiki/Dried_Kelp  > wiki/Dried_Kelp.html
curl https://minecraft.fandom.com/wiki/Glow_Berries  > wiki/Glow_Berries.html
curl https://minecraft.fandom.com/wiki/Honey_Bottle  > wiki/Honey_Bottle.html
curl https://minecraft.fandom.com/wiki/Melon_Slice  > wiki/Melon_Slice.html
curl https://minecraft.fandom.com/wiki/Mushroom_Stew  > wiki/Mushroom_Stew.html
curl https://minecraft.fandom.com/wiki/Beetroot_Soup  > wiki/Beetroot_Soup.html
curl https://minecraft.fandom.com/wiki/Rabbit_Stew  > wiki/Rabbit_Stew.html
curl https://minecraft.fandom.com/wiki/Suspicious_Stew  > wiki/Suspicious_Stew.html
curl https://minecraft.fandom.com/wiki/Potato  > wiki/Potato.html
curl https://minecraft.fandom.com/wiki/Baked_Potato  > wiki/Baked_Potato.html
curl https://minecraft.fandom.com/wiki/Poisonous_Potato  > wiki/Poisonous_Potato.html
curl https://minecraft.fandom.com/wiki/Pufferfish_\(item\)  > wiki/Pufferfish_\(item\).html
curl https://minecraft.fandom.com/wiki/Pumpkin_Pie  > wiki/Pumpkin_Pie.html
curl https://minecraft.fandom.com/wiki/Raw_Beef  > wiki/Raw_Beef.html
curl https://minecraft.fandom.com/wiki/Steak  > wiki/Steak.html
curl https://minecraft.fandom.com/wiki/Raw_Chicken  > wiki/Raw_Chicken.html
curl https://minecraft.fandom.com/wiki/Cooked_Chicken  > wiki/Cooked_Chicken.html
curl https://minecraft.fandom.com/wiki/Raw_Cod  > wiki/Raw_Cod.html
curl https://minecraft.fandom.com/wiki/Cooked_Cod  > wiki/Cooked_Cod.html
curl https://minecraft.fandom.com/wiki/Raw_Mutton  > wiki/Raw_Mutton.html
curl https://minecraft.fandom.com/wiki/Cooked_Mutton  > wiki/Cooked_Mutton.html
curl https://minecraft.fandom.com/wiki/Raw_Porkchop  > wiki/Raw_Porkchop.html
curl https://minecraft.fandom.com/wiki/Cooked_Porkchop  > wiki/Cooked_Porkchop.html
curl https://minecraft.fandom.com/wiki/Raw_Rabbit  > wiki/Raw_Rabbit.html
curl https://minecraft.fandom.com/wiki/Cooked_Rabbit  > wiki/Cooked_Rabbit.html
curl https://minecraft.fandom.com/wiki/Raw_Salmon  > wiki/Raw_Salmon.html
curl https://minecraft.fandom.com/wiki/Cooked_Salmon  > wiki/Cooked_Salmon.html
curl https://minecraft.fandom.com/wiki/Rotten_Flesh  > wiki/Rotten_Flesh.html
curl https://minecraft.fandom.com/wiki/Spider_Eye  > wiki/Spider_Eye.html
curl https://minecraft.fandom.com/wiki/Sweet_Berries  > wiki/Sweet_Berries.html
curl https://minecraft.fandom.com/wiki/Tropical_Fish_\(item\)  > wiki/Tropical_Fish_\(item\).html
curl https://minecraft.fandom.com/wiki/Dye  > wiki/Dye.html
curl https://minecraft.fandom.com/wiki/Black_Dye  > wiki/Black_Dye.html
curl https://minecraft.fandom.com/wiki/Blue_Dye  > wiki/Blue_Dye.html
curl https://minecraft.fandom.com/wiki/Brown_Dye  > wiki/Brown_Dye.html
curl https://minecraft.fandom.com/wiki/Cyan_Dye  > wiki/Cyan_Dye.html
curl https://minecraft.fandom.com/wiki/Gray_Dye  > wiki/Gray_Dye.html
curl https://minecraft.fandom.com/wiki/Green_Dye  > wiki/Green_Dye.html
curl https://minecraft.fandom.com/wiki/Light_Blue_Dye  > wiki/Light_Blue_Dye.html
curl https://minecraft.fandom.com/wiki/Light_Gray_Dye  > wiki/Light_Gray_Dye.html
curl https://minecraft.fandom.com/wiki/Lime_Dye  > wiki/Lime_Dye.html
curl https://minecraft.fandom.com/wiki/Magenta_Dye  > wiki/Magenta_Dye.html
curl https://minecraft.fandom.com/wiki/Orange_Dye  > wiki/Orange_Dye.html
curl https://minecraft.fandom.com/wiki/Pink_Dye  > wiki/Pink_Dye.html
curl https://minecraft.fandom.com/wiki/Purple_Dye  > wiki/Purple_Dye.html
curl https://minecraft.fandom.com/wiki/Red_Dye  > wiki/Red_Dye.html
curl https://minecraft.fandom.com/wiki/White_Dye  > wiki/White_Dye.html
curl https://minecraft.fandom.com/wiki/Yellow_Dye  > wiki/Yellow_Dye.html
curl https://minecraft.fandom.com/wiki/Tool  > wiki/Tool.html
curl https://minecraft.fandom.com/wiki/Axe  > wiki/Axe.html
curl https://minecraft.fandom.com/wiki/Fishing_Rod  > wiki/Fishing_Rod.html
curl https://minecraft.fandom.com/wiki/Flint_and_Steel  > wiki/Flint_and_Steel.html
curl https://minecraft.fandom.com/wiki/Hoe  > wiki/Hoe.html
curl https://minecraft.fandom.com/wiki/Pickaxe  > wiki/Pickaxe.html
curl https://minecraft.fandom.com/wiki/Potion  > wiki/Potion.html
curl https://minecraft.fandom.com/wiki/Lingering_Potion  > wiki/Lingering_Potion.html
curl https://minecraft.fandom.com/wiki/Splash_Potion  > wiki/Splash_Potion.html
curl https://minecraft.fandom.com/wiki/Shears  > wiki/Shears.html
curl https://minecraft.fandom.com/wiki/Shovel  > wiki/Shovel.html
curl https://minecraft.fandom.com/wiki/BE  > wiki/BE.html
curl https://minecraft.fandom.com/wiki/EE  > wiki/EE.html
curl https://minecraft.fandom.com/wiki/Medicine  > wiki/Medicine.html
curl https://minecraft.fandom.com/wiki/Weapons  > wiki/Weapons.html
curl https://minecraft.fandom.com/wiki/Arrow  > wiki/Arrow.html
curl https://minecraft.fandom.com/wiki/Arrow  > wiki/Arrow.html
curl https://minecraft.fandom.com/wiki/Bow  > wiki/Bow.html
curl https://minecraft.fandom.com/wiki/Crossbow  > wiki/Crossbow.html
curl https://minecraft.fandom.com/wiki/Egg  > wiki/Egg.html
curl https://minecraft.fandom.com/wiki/Fire_Charge  > wiki/Fire_Charge.html
curl https://minecraft.fandom.com/wiki/Shield  > wiki/Shield.html
curl https://minecraft.fandom.com/wiki/Snowball  > wiki/Snowball.html
curl https://minecraft.fandom.com/wiki/Sword  > wiki/Sword.html
curl https://minecraft.fandom.com/wiki/Trident  > wiki/Trident.html
curl https://minecraft.fandom.com/wiki/Java_Edition  > wiki/Java_Edition.html
curl https://minecraft.fandom.com/wiki/Arrow  > wiki/Arrow.html
curl https://minecraft.fandom.com/wiki/BE  > wiki/BE.html
curl https://minecraft.fandom.com/wiki/EE  > wiki/EE.html
curl https://minecraft.fandom.com/wiki/Ice_Bomb  > wiki/Ice_Bomb.html
curl https://minecraft.fandom.com/wiki/Armor  > wiki/Armor.html
curl https://minecraft.fandom.com/wiki/Boots  > wiki/Boots.html
curl https://minecraft.fandom.com/wiki/Chestplate  > wiki/Chestplate.html
curl https://minecraft.fandom.com/wiki/Helmet  > wiki/Helmet.html
curl https://minecraft.fandom.com/wiki/Turtle_Shell  > wiki/Turtle_Shell.html
curl https://minecraft.fandom.com/wiki/Horse_Armor  > wiki/Horse_Armor.html
curl https://minecraft.fandom.com/wiki/Leggings  > wiki/Leggings.html
curl https://minecraft.fandom.com/wiki/Book_and_Quill  > wiki/Book_and_Quill.html
curl https://minecraft.fandom.com/wiki/Written_Book  > wiki/Written_Book.html
curl https://minecraft.fandom.com/wiki/Clock  > wiki/Clock.html
curl https://minecraft.fandom.com/wiki/Compass  > wiki/Compass.html
curl https://minecraft.fandom.com/wiki/Recovery_Compass  > wiki/Recovery_Compass.html
curl https://minecraft.fandom.com/wiki/Map  > wiki/Map.html
curl https://minecraft.fandom.com/wiki/Map  > wiki/Map.html
curl https://minecraft.fandom.com/wiki/Explorer_Map  > wiki/Explorer_Map.html
curl https://minecraft.fandom.com/wiki/Name_Tag  > wiki/Name_Tag.html
curl https://minecraft.fandom.com/wiki/Spyglass  > wiki/Spyglass.html
curl https://minecraft.fandom.com/wiki/Transportation  > wiki/Transportation.html
curl https://minecraft.fandom.com/wiki/Boat  > wiki/Boat.html
curl https://minecraft.fandom.com/wiki/Boat_with_Chest  > wiki/Boat_with_Chest.html
curl https://minecraft.fandom.com/wiki/Elytra  > wiki/Elytra.html
curl https://minecraft.fandom.com/wiki/Minecart  > wiki/Minecart.html
curl https://minecraft.fandom.com/wiki/Minecart_with_Chest  > wiki/Minecart_with_Chest.html
curl https://minecraft.fandom.com/wiki/Minecart_with_Hopper  > wiki/Minecart_with_Hopper.html
curl https://minecraft.fandom.com/wiki/Minecart_with_TNT  > wiki/Minecart_with_TNT.html
curl https://minecraft.fandom.com/wiki/Java_Edition  > wiki/Java_Edition.html
curl https://minecraft.fandom.com/wiki/Minecart_with_Furnace  > wiki/Minecart_with_Furnace.html
curl https://minecraft.fandom.com/wiki/Armor_Stand  > wiki/Armor_Stand.html
curl https://minecraft.fandom.com/wiki/Banner_Pattern  > wiki/Banner_Pattern.html
curl https://minecraft.fandom.com/wiki/Bone_Meal  > wiki/Bone_Meal.html
curl https://minecraft.fandom.com/wiki/Bottle_o%27_Enchanting  > wiki/Bottle_o%27_Enchanting.html
curl https://minecraft.fandom.com/wiki/Bowl  > wiki/Bowl.html
curl https://minecraft.fandom.com/wiki/Bucket  > wiki/Bucket.html
curl https://minecraft.fandom.com/wiki/Water_Bucket  > wiki/Water_Bucket.html
curl https://minecraft.fandom.com/wiki/Lava_Bucket  > wiki/Lava_Bucket.html
curl https://minecraft.fandom.com/wiki/Milk_Bucket  > wiki/Milk_Bucket.html
curl https://minecraft.fandom.com/wiki/Powder_Snow_Bucket  > wiki/Powder_Snow_Bucket.html
curl https://minecraft.fandom.com/wiki/Bucket_of_Axolotl  > wiki/Bucket_of_Axolotl.html
curl https://minecraft.fandom.com/wiki/Bucket_of_Cod  > wiki/Bucket_of_Cod.html
curl https://minecraft.fandom.com/wiki/Bucket_of_Pufferfish  > wiki/Bucket_of_Pufferfish.html
curl https://minecraft.fandom.com/wiki/Bucket_of_Salmon  > wiki/Bucket_of_Salmon.html
curl https://minecraft.fandom.com/wiki/Bucket_of_Tadpole  > wiki/Bucket_of_Tadpole.html
curl https://minecraft.fandom.com/wiki/Bucket_of_Tropical_Fish  > wiki/Bucket_of_Tropical_Fish.html
curl https://minecraft.fandom.com/wiki/Carrot_on_a_Stick  > wiki/Carrot_on_a_Stick.html
curl https://minecraft.fandom.com/wiki/Warped_Fungus_on_a_Stick  > wiki/Warped_Fungus_on_a_Stick.html
curl https://minecraft.fandom.com/wiki/Enchanted_Book  > wiki/Enchanted_Book.html
curl https://minecraft.fandom.com/wiki/End_Crystal  > wiki/End_Crystal.html
curl https://minecraft.fandom.com/wiki/Eye_of_Ender  > wiki/Eye_of_Ender.html
curl https://minecraft.fandom.com/wiki/Firework_Rocket  > wiki/Firework_Rocket.html
curl https://minecraft.fandom.com/wiki/Glass_Bottle  > wiki/Glass_Bottle.html
curl https://minecraft.fandom.com/wiki/Water_Bottle  > wiki/Water_Bottle.html
curl https://minecraft.fandom.com/wiki/Goat_Horn  > wiki/Goat_Horn.html
curl https://minecraft.fandom.com/wiki/Lead  > wiki/Lead.html
curl https://minecraft.fandom.com/wiki/Saddle  > wiki/Saddle.html
curl https://minecraft.fandom.com/wiki/Totem_of_Undying  > wiki/Totem_of_Undying.html
curl https://minecraft.fandom.com/wiki/BE  > wiki/BE.html
curl https://minecraft.fandom.com/wiki/EE  > wiki/EE.html
curl https://minecraft.fandom.com/wiki/Balloon  > wiki/Balloon.html
curl https://minecraft.fandom.com/wiki/Sparkler  > wiki/Sparkler.html
curl https://minecraft.fandom.com/wiki/Glow_Stick  > wiki/Glow_Stick.html
curl https://minecraft.fandom.com/wiki/Super_Fertilizer  > wiki/Super_Fertilizer.html
curl https://minecraft.fandom.com/wiki/Item_Frame  > wiki/Item_Frame.html
curl https://minecraft.fandom.com/wiki/Glow_Item_Frame  > wiki/Glow_Item_Frame.html
curl https://minecraft.fandom.com/wiki/Music_Disc  > wiki/Music_Disc.html
curl https://minecraft.fandom.com/wiki/Painting  > wiki/Painting.html
curl https://minecraft.fandom.com/wiki/Creative  > wiki/Creative.html
curl https://minecraft.fandom.com/wiki/Spawn_Egg  > wiki/Spawn_Egg.html
curl https://minecraft.fandom.com/wiki/Commands  > wiki/Commands.html
curl https://minecraft.fandom.com/wiki/Minecart_with_Command_Block  > wiki/Minecart_with_Command_Block.html
curl https://minecraft.fandom.com/wiki/Java_Edition  > wiki/Java_Edition.html
curl https://minecraft.fandom.com/wiki/Bundle  > wiki/Bundle.html
curl https://minecraft.fandom.com/wiki/Debug_Stick  > wiki/Debug_Stick.html
curl https://minecraft.fandom.com/wiki/Knowledge_Book  > wiki/Knowledge_Book.html
curl https://minecraft.fandom.com/wiki/Education_Edition  > wiki/Education_Edition.html
curl https://minecraft.fandom.com/wiki/Camera  > wiki/Camera.html
curl https://minecraft.fandom.com/wiki/Portfolio  > wiki/Portfolio.html
curl https://minecraft.fandom.com/wiki/Photo  > wiki/Photo.html
curl https://minecraft.fandom.com/wiki/Mundane_Potion  > wiki/Mundane_Potion.html
curl https://minecraft.fandom.com/wiki/Thick_Potion  > wiki/Thick_Potion.html
curl https://minecraft.fandom.com/wiki/Java_Edition  > wiki/Java_Edition.html
curl https://minecraft.fandom.com/wiki/Potion_of_Luck  > wiki/Potion_of_Luck.html
curl https://minecraft.fandom.com/wiki/Uncraftable_Potion  > wiki/Uncraftable_Potion.html
curl https://minecraft.fandom.com/wiki/Bedrock_Edition  > wiki/Bedrock_Edition.html
curl https://minecraft.fandom.com/wiki/Potion_of_Decay  > wiki/Potion_of_Decay.html
curl https://minecraft.fandom.com/wiki/Potion#Unused_potions  > wiki/Potion#Unused_potions.html
curl https://minecraft.fandom.com/wiki/Java_Edition_removed_features#Quiver  > wiki/Java_Edition_removed_features#Quiver.html
curl https://minecraft.fandom.com/wiki/Emerald#History  > wiki/Emerald#History.html
curl https://minecraft.fandom.com/wiki/Java_Edition  > wiki/Java_Edition.html
curl https://minecraft.fandom.com/wiki/Crystallized_Honey  > wiki/Crystallized_Honey.html
curl https://minecraft.fandom.com/wiki/Minecart_with_Dispenser  > wiki/Minecart_with_Dispenser.html
curl https://minecraft.fandom.com/wiki/Java_Edition_removed_features#Studded_armor  > wiki/Java_Edition_removed_features#Studded_armor.html
curl https://minecraft.fandom.com/wiki/Bedrock_Edition  > wiki/Bedrock_Edition.html
curl https://minecraft.fandom.com/wiki/Minecart_with_Furnace  > wiki/Minecart_with_Furnace.html
curl https://minecraft.fandom.com/wiki/Hoglin#Trivia  > wiki/Hoglin#Trivia.html
curl https://minecraft.fandom.com/wiki/Java_Edition_15w14a  > wiki/Java_Edition_15w14a.html
curl https://minecraft.fandom.com/wiki/Obsidian_Boat  > wiki/Obsidian_Boat.html
curl https://minecraft.fandom.com/wiki/Java_Edition_1.RV-Pre1  > wiki/Java_Edition_1.RV-Pre1.html
curl https://minecraft.fandom.com/wiki/Smarter_Watch  > wiki/Smarter_Watch.html
curl https://minecraft.fandom.com/wiki/Reality_Vision  > wiki/Reality_Vision.html
curl https://minecraft.fandom.com/wiki/Ankle_Monitor  > wiki/Ankle_Monitor.html
curl https://minecraft.fandom.com/wiki/Java_Edition_3D_Shareware_v1.34  > wiki/Java_Edition_3D_Shareware_v1.34.html
curl https://minecraft.fandom.com/wiki/3D  > wiki/3D.html
curl https://minecraft.fandom.com/wiki/Blue_Key  > wiki/Blue_Key.html
curl https://minecraft.fandom.com/wiki/Red_Key  > wiki/Red_Key.html
curl https://minecraft.fandom.com/wiki/Yellow_Key  > wiki/Yellow_Key.html
curl https://minecraft.fandom.com/wiki/Java_Edition_20w14%E2%88%9E  > wiki/Java_Edition_20w14%E2%88%9E.html
curl https://minecraft.fandom.com/wiki/Footprint  > wiki/Footprint.html
curl https://minecraft.fandom.com/wiki/A_Very_Fine_Item  > wiki/A_Very_Fine_Item.html
curl https://minecraft.fandom.com/wiki/Java_Edition  > wiki/Java_Edition.html
curl https://minecraft.fandom.com/wiki/Java_Edition_removed_items#Potions  > wiki/Java_Edition_removed_items#Potions.html
curl https://minecraft.fandom.com/wiki/Horse_Saddle  > wiki/Horse_Saddle.html
curl https://minecraft.fandom.com/wiki/Java_Edition_removed_items#Reverted_potions  > wiki/Java_Edition_removed_items#Reverted_potions.html
curl https://minecraft.fandom.com/wiki/Bedrock_Edition  > wiki/Bedrock_Edition.html
curl https://minecraft.fandom.com/wiki/Camera  > wiki/Camera.html
curl https://minecraft.fandom.com/wiki/Copper_Horn  > wiki/Copper_Horn.html
curl https://minecraft.fandom.com/wiki/MinecraftEdu  > wiki/MinecraftEdu.html
curl https://minecraft.fandom.com/wiki/Block_Inspector  > wiki/Block_Inspector.html
npx prettier --write .