#!/bin/sh
# Get and format HTML of each item's page
curl https://minecraft.fandom.com/wiki/Item > Item.html
curl https://minecraft.fandom.com/wiki/Item > Item.html
curl https://minecraft.fandom.com/wiki/Amethyst_Shard > Amethyst_Shard.html
curl https://minecraft.fandom.com/wiki/Blaze_Rod > Blaze_Rod.html
curl https://minecraft.fandom.com/wiki/Bone > Bone.html
curl https://minecraft.fandom.com/wiki/Clay_Ball > Clay_Ball.html
curl https://minecraft.fandom.com/wiki/Coal > Coal.html
curl https://minecraft.fandom.com/wiki/Diamond > Diamond.html
curl https://minecraft.fandom.com/wiki/Disc_Fragment_5 > Disc_Fragment_5.html
curl https://minecraft.fandom.com/wiki/Dragon%27s_Breath > Dragon%27s_Breath.html
curl https://minecraft.fandom.com/wiki/Echo_Shard > Echo_Shard.html
curl https://minecraft.fandom.com/wiki/Emerald > Emerald.html
curl https://minecraft.fandom.com/wiki/Ender_Pearl > Ender_Pearl.html
curl https://minecraft.fandom.com/wiki/Feather > Feather.html
curl https://minecraft.fandom.com/wiki/Flint > Flint.html
curl https://minecraft.fandom.com/wiki/Ghast_Tear > Ghast_Tear.html
curl https://minecraft.fandom.com/wiki/Glowstone_Dust > Glowstone_Dust.html
curl https://minecraft.fandom.com/wiki/Gunpowder > Gunpowder.html
curl https://minecraft.fandom.com/wiki/Heart_of_the_Sea > Heart_of_the_Sea.html
curl https://minecraft.fandom.com/wiki/Honeycomb > Honeycomb.html
curl https://minecraft.fandom.com/wiki/Ink_Sac > Ink_Sac.html
curl https://minecraft.fandom.com/wiki/Glow_Ink_Sac > Glow_Ink_Sac.html
curl https://minecraft.fandom.com/wiki/Lapis_Lazuli > Lapis_Lazuli.html
curl https://minecraft.fandom.com/wiki/Leather > Leather.html
curl https://minecraft.fandom.com/wiki/Magma_Cream > Magma_Cream.html
curl https://minecraft.fandom.com/wiki/Nautilus_Shell > Nautilus_Shell.html
curl https://minecraft.fandom.com/wiki/Nether_Quartz > Nether_Quartz.html
curl https://minecraft.fandom.com/wiki/Nether_Star > Nether_Star.html
curl https://minecraft.fandom.com/wiki/Nether_Wart > Nether_Wart.html
curl https://minecraft.fandom.com/wiki/Phantom_Membrane > Phantom_Membrane.html
curl https://minecraft.fandom.com/wiki/Prismarine_Shard > Prismarine_Shard.html
curl https://minecraft.fandom.com/wiki/Prismarine_Crystals > Prismarine_Crystals.html
curl https://minecraft.fandom.com/wiki/Rabbit_Hide > Rabbit_Hide.html
curl https://minecraft.fandom.com/wiki/Rabbit%27s_Foot > Rabbit%27s_Foot.html
curl https://minecraft.fandom.com/wiki/Raw_Copper > Raw_Copper.html
curl https://minecraft.fandom.com/wiki/Raw_Gold > Raw_Gold.html
curl https://minecraft.fandom.com/wiki/Raw_Iron > Raw_Iron.html
curl https://minecraft.fandom.com/wiki/Redstone_Dust > Redstone_Dust.html
curl https://minecraft.fandom.com/wiki/Scute > Scute.html
curl https://minecraft.fandom.com/wiki/Shulker_Shell > Shulker_Shell.html
curl https://minecraft.fandom.com/wiki/Slimeball > Slimeball.html
curl https://minecraft.fandom.com/wiki/Stick > Stick.html
curl https://minecraft.fandom.com/wiki/String > String.html
curl https://minecraft.fandom.com/wiki/Wheat > Wheat.html
curl https://minecraft.fandom.com/wiki/Blaze_Powder > Blaze_Powder.html
curl https://minecraft.fandom.com/wiki/Book > Book.html
curl https://minecraft.fandom.com/wiki/Brick > Brick.html
curl https://minecraft.fandom.com/wiki/Nether_Brick > Nether_Brick.html
curl https://minecraft.fandom.com/wiki/Charcoal > Charcoal.html
curl https://minecraft.fandom.com/wiki/Copper_Ingot > Copper_Ingot.html
curl https://minecraft.fandom.com/wiki/Fermented_Spider_Eye > Fermented_Spider_Eye.html
curl https://minecraft.fandom.com/wiki/Firework_Star > Firework_Star.html
curl https://minecraft.fandom.com/wiki/Glistering_Melon_Slice > Glistering_Melon_Slice.html
curl https://minecraft.fandom.com/wiki/Gold_Ingot > Gold_Ingot.html
curl https://minecraft.fandom.com/wiki/Gold_Nugget > Gold_Nugget.html
curl https://minecraft.fandom.com/wiki/Iron_Ingot > Iron_Ingot.html
curl https://minecraft.fandom.com/wiki/Iron_Nugget > Iron_Nugget.html
curl https://minecraft.fandom.com/wiki/Netherite_Ingot > Netherite_Ingot.html
curl https://minecraft.fandom.com/wiki/Netherite_Scrap > Netherite_Scrap.html
curl https://minecraft.fandom.com/wiki/Paper > Paper.html
curl https://minecraft.fandom.com/wiki/Popped_Chorus_Fruit > Popped_Chorus_Fruit.html
curl https://minecraft.fandom.com/wiki/Sugar > Sugar.html
curl https://minecraft.fandom.com/wiki/BE > BE.html
curl https://minecraft.fandom.com/wiki/EE > EE.html
curl https://minecraft.fandom.com/wiki/Bleach > Bleach.html
curl https://minecraft.fandom.com/wiki/Compound > Compound.html
curl https://minecraft.fandom.com/wiki/Beetroot_Seeds > Beetroot_Seeds.html
curl https://minecraft.fandom.com/wiki/Cocoa_Beans > Cocoa_Beans.html
curl https://minecraft.fandom.com/wiki/Melon_Seeds > Melon_Seeds.html
curl https://minecraft.fandom.com/wiki/Pumpkin_Seeds > Pumpkin_Seeds.html
curl https://minecraft.fandom.com/wiki/Wheat_Seeds > Wheat_Seeds.html
curl https://minecraft.fandom.com/wiki/Food > Food.html
curl https://minecraft.fandom.com/wiki/Apple > Apple.html
curl https://minecraft.fandom.com/wiki/Golden_Apple > Golden_Apple.html
curl https://minecraft.fandom.com/wiki/Enchanted_Golden_Apple > Enchanted_Golden_Apple.html
curl https://minecraft.fandom.com/wiki/Beetroot > Beetroot.html
curl https://minecraft.fandom.com/wiki/Bread > Bread.html
curl https://minecraft.fandom.com/wiki/Carrot > Carrot.html
curl https://minecraft.fandom.com/wiki/Golden_Carrot > Golden_Carrot.html
curl https://minecraft.fandom.com/wiki/Chorus_Fruit > Chorus_Fruit.html
curl https://minecraft.fandom.com/wiki/Cookie > Cookie.html
curl https://minecraft.fandom.com/wiki/Dried_Kelp > Dried_Kelp.html
curl https://minecraft.fandom.com/wiki/Glow_Berries > Glow_Berries.html
curl https://minecraft.fandom.com/wiki/Honey_Bottle > Honey_Bottle.html
curl https://minecraft.fandom.com/wiki/Melon_Slice > Melon_Slice.html
curl https://minecraft.fandom.com/wiki/Mushroom_Stew > Mushroom_Stew.html
curl https://minecraft.fandom.com/wiki/Beetroot_Soup > Beetroot_Soup.html
curl https://minecraft.fandom.com/wiki/Rabbit_Stew > Rabbit_Stew.html
curl https://minecraft.fandom.com/wiki/Suspicious_Stew > Suspicious_Stew.html
curl https://minecraft.fandom.com/wiki/Potato > Potato.html
curl https://minecraft.fandom.com/wiki/Baked_Potato > Baked_Potato.html
curl https://minecraft.fandom.com/wiki/Poisonous_Potato > Poisonous_Potato.html
curl https://minecraft.fandom.com/wiki/Pufferfish_\(item\) > Pufferfish_\(item\).html
curl https://minecraft.fandom.com/wiki/Pumpkin_Pie > Pumpkin_Pie.html
curl https://minecraft.fandom.com/wiki/Raw_Beef > Raw_Beef.html
curl https://minecraft.fandom.com/wiki/Steak > Steak.html
curl https://minecraft.fandom.com/wiki/Raw_Chicken > Raw_Chicken.html
curl https://minecraft.fandom.com/wiki/Cooked_Chicken > Cooked_Chicken.html
curl https://minecraft.fandom.com/wiki/Raw_Cod > Raw_Cod.html
curl https://minecraft.fandom.com/wiki/Cooked_Cod > Cooked_Cod.html
curl https://minecraft.fandom.com/wiki/Raw_Mutton > Raw_Mutton.html
curl https://minecraft.fandom.com/wiki/Cooked_Mutton > Cooked_Mutton.html
curl https://minecraft.fandom.com/wiki/Raw_Porkchop > Raw_Porkchop.html
curl https://minecraft.fandom.com/wiki/Cooked_Porkchop > Cooked_Porkchop.html
curl https://minecraft.fandom.com/wiki/Raw_Rabbit > Raw_Rabbit.html
curl https://minecraft.fandom.com/wiki/Cooked_Rabbit > Cooked_Rabbit.html
curl https://minecraft.fandom.com/wiki/Raw_Salmon > Raw_Salmon.html
curl https://minecraft.fandom.com/wiki/Cooked_Salmon > Cooked_Salmon.html
curl https://minecraft.fandom.com/wiki/Rotten_Flesh > Rotten_Flesh.html
curl https://minecraft.fandom.com/wiki/Spider_Eye > Spider_Eye.html
curl https://minecraft.fandom.com/wiki/Sweet_Berries > Sweet_Berries.html
curl https://minecraft.fandom.com/wiki/Tropical_Fish_\(item\) > Tropical_Fish_\(item\).html
curl https://minecraft.fandom.com/wiki/Dye > Dye.html
curl https://minecraft.fandom.com/wiki/Black_Dye > Black_Dye.html
curl https://minecraft.fandom.com/wiki/Blue_Dye > Blue_Dye.html
curl https://minecraft.fandom.com/wiki/Brown_Dye > Brown_Dye.html
curl https://minecraft.fandom.com/wiki/Cyan_Dye > Cyan_Dye.html
curl https://minecraft.fandom.com/wiki/Gray_Dye > Gray_Dye.html
curl https://minecraft.fandom.com/wiki/Green_Dye > Green_Dye.html
curl https://minecraft.fandom.com/wiki/Light_Blue_Dye > Light_Blue_Dye.html
curl https://minecraft.fandom.com/wiki/Light_Gray_Dye > Light_Gray_Dye.html
curl https://minecraft.fandom.com/wiki/Lime_Dye > Lime_Dye.html
curl https://minecraft.fandom.com/wiki/Magenta_Dye > Magenta_Dye.html
curl https://minecraft.fandom.com/wiki/Orange_Dye > Orange_Dye.html
curl https://minecraft.fandom.com/wiki/Pink_Dye > Pink_Dye.html
curl https://minecraft.fandom.com/wiki/Purple_Dye > Purple_Dye.html
curl https://minecraft.fandom.com/wiki/Red_Dye > Red_Dye.html
curl https://minecraft.fandom.com/wiki/White_Dye > White_Dye.html
curl https://minecraft.fandom.com/wiki/Yellow_Dye > Yellow_Dye.html
curl https://minecraft.fandom.com/wiki/Tool > Tool.html
curl https://minecraft.fandom.com/wiki/Axe > Axe.html
curl https://minecraft.fandom.com/wiki/Fishing_Rod > Fishing_Rod.html
curl https://minecraft.fandom.com/wiki/Flint_and_Steel > Flint_and_Steel.html
curl https://minecraft.fandom.com/wiki/Hoe > Hoe.html
curl https://minecraft.fandom.com/wiki/Pickaxe > Pickaxe.html
curl https://minecraft.fandom.com/wiki/Potion > Potion.html
curl https://minecraft.fandom.com/wiki/Lingering_Potion > Lingering_Potion.html
curl https://minecraft.fandom.com/wiki/Splash_Potion > Splash_Potion.html
curl https://minecraft.fandom.com/wiki/Shears > Shears.html
curl https://minecraft.fandom.com/wiki/Shovel > Shovel.html
curl https://minecraft.fandom.com/wiki/BE > BE.html
curl https://minecraft.fandom.com/wiki/EE > EE.html
curl https://minecraft.fandom.com/wiki/Medicine > Medicine.html
curl https://minecraft.fandom.com/wiki/Weapons > Weapons.html
curl https://minecraft.fandom.com/wiki/Arrow > Arrow.html
curl https://minecraft.fandom.com/wiki/Arrow > Arrow.html
curl https://minecraft.fandom.com/wiki/Bow > Bow.html
curl https://minecraft.fandom.com/wiki/Crossbow > Crossbow.html
curl https://minecraft.fandom.com/wiki/Egg > Egg.html
curl https://minecraft.fandom.com/wiki/Fire_Charge > Fire_Charge.html
curl https://minecraft.fandom.com/wiki/Shield > Shield.html
curl https://minecraft.fandom.com/wiki/Snowball > Snowball.html
curl https://minecraft.fandom.com/wiki/Sword > Sword.html
curl https://minecraft.fandom.com/wiki/Trident > Trident.html
curl https://minecraft.fandom.com/wiki/Java_Edition > Java_Edition.html
curl https://minecraft.fandom.com/wiki/Arrow > Arrow.html
curl https://minecraft.fandom.com/wiki/BE > BE.html
curl https://minecraft.fandom.com/wiki/EE > EE.html
curl https://minecraft.fandom.com/wiki/Ice_Bomb > Ice_Bomb.html
curl https://minecraft.fandom.com/wiki/Armor > Armor.html
curl https://minecraft.fandom.com/wiki/Boots > Boots.html
curl https://minecraft.fandom.com/wiki/Chestplate > Chestplate.html
curl https://minecraft.fandom.com/wiki/Helmet > Helmet.html
curl https://minecraft.fandom.com/wiki/Turtle_Shell > Turtle_Shell.html
curl https://minecraft.fandom.com/wiki/Horse_Armor > Horse_Armor.html
curl https://minecraft.fandom.com/wiki/Leggings > Leggings.html
curl https://minecraft.fandom.com/wiki/Book_and_Quill > Book_and_Quill.html
curl https://minecraft.fandom.com/wiki/Written_Book > Written_Book.html
curl https://minecraft.fandom.com/wiki/Clock > Clock.html
curl https://minecraft.fandom.com/wiki/Compass > Compass.html
curl https://minecraft.fandom.com/wiki/Recovery_Compass > Recovery_Compass.html
curl https://minecraft.fandom.com/wiki/Map > Map.html
curl https://minecraft.fandom.com/wiki/Map > Map.html
curl https://minecraft.fandom.com/wiki/Explorer_Map > Explorer_Map.html
curl https://minecraft.fandom.com/wiki/Name_Tag > Name_Tag.html
curl https://minecraft.fandom.com/wiki/Spyglass > Spyglass.html
curl https://minecraft.fandom.com/wiki/Transportation > Transportation.html
curl https://minecraft.fandom.com/wiki/Boat > Boat.html
curl https://minecraft.fandom.com/wiki/Boat_with_Chest > Boat_with_Chest.html
curl https://minecraft.fandom.com/wiki/Elytra > Elytra.html
curl https://minecraft.fandom.com/wiki/Minecart > Minecart.html
curl https://minecraft.fandom.com/wiki/Minecart_with_Chest > Minecart_with_Chest.html
curl https://minecraft.fandom.com/wiki/Minecart_with_Hopper > Minecart_with_Hopper.html
curl https://minecraft.fandom.com/wiki/Minecart_with_TNT > Minecart_with_TNT.html
curl https://minecraft.fandom.com/wiki/Java_Edition > Java_Edition.html
curl https://minecraft.fandom.com/wiki/Minecart_with_Furnace > Minecart_with_Furnace.html
curl https://minecraft.fandom.com/wiki/Armor_Stand > Armor_Stand.html
curl https://minecraft.fandom.com/wiki/Banner_Pattern > Banner_Pattern.html
curl https://minecraft.fandom.com/wiki/Bone_Meal > Bone_Meal.html
curl https://minecraft.fandom.com/wiki/Bottle_o%27_Enchanting > Bottle_o%27_Enchanting.html
curl https://minecraft.fandom.com/wiki/Bowl > Bowl.html
curl https://minecraft.fandom.com/wiki/Bucket > Bucket.html
curl https://minecraft.fandom.com/wiki/Water_Bucket > Water_Bucket.html
curl https://minecraft.fandom.com/wiki/Lava_Bucket > Lava_Bucket.html
curl https://minecraft.fandom.com/wiki/Milk_Bucket > Milk_Bucket.html
curl https://minecraft.fandom.com/wiki/Powder_Snow_Bucket > Powder_Snow_Bucket.html
curl https://minecraft.fandom.com/wiki/Bucket_of_Axolotl > Bucket_of_Axolotl.html
curl https://minecraft.fandom.com/wiki/Bucket_of_Cod > Bucket_of_Cod.html
curl https://minecraft.fandom.com/wiki/Bucket_of_Pufferfish > Bucket_of_Pufferfish.html
curl https://minecraft.fandom.com/wiki/Bucket_of_Salmon > Bucket_of_Salmon.html
curl https://minecraft.fandom.com/wiki/Bucket_of_Tadpole > Bucket_of_Tadpole.html
curl https://minecraft.fandom.com/wiki/Bucket_of_Tropical_Fish > Bucket_of_Tropical_Fish.html
curl https://minecraft.fandom.com/wiki/Carrot_on_a_Stick > Carrot_on_a_Stick.html
curl https://minecraft.fandom.com/wiki/Warped_Fungus_on_a_Stick > Warped_Fungus_on_a_Stick.html
curl https://minecraft.fandom.com/wiki/Enchanted_Book > Enchanted_Book.html
curl https://minecraft.fandom.com/wiki/End_Crystal > End_Crystal.html
curl https://minecraft.fandom.com/wiki/Eye_of_Ender > Eye_of_Ender.html
curl https://minecraft.fandom.com/wiki/Firework_Rocket > Firework_Rocket.html
curl https://minecraft.fandom.com/wiki/Glass_Bottle > Glass_Bottle.html
curl https://minecraft.fandom.com/wiki/Water_Bottle > Water_Bottle.html
curl https://minecraft.fandom.com/wiki/Goat_Horn > Goat_Horn.html
curl https://minecraft.fandom.com/wiki/Lead > Lead.html
curl https://minecraft.fandom.com/wiki/Saddle > Saddle.html
curl https://minecraft.fandom.com/wiki/Totem_of_Undying > Totem_of_Undying.html
curl https://minecraft.fandom.com/wiki/BE > BE.html
curl https://minecraft.fandom.com/wiki/EE > EE.html
curl https://minecraft.fandom.com/wiki/Balloon > Balloon.html
curl https://minecraft.fandom.com/wiki/Sparkler > Sparkler.html
curl https://minecraft.fandom.com/wiki/Glow_Stick > Glow_Stick.html
curl https://minecraft.fandom.com/wiki/Super_Fertilizer > Super_Fertilizer.html
curl https://minecraft.fandom.com/wiki/Item_Frame > Item_Frame.html
curl https://minecraft.fandom.com/wiki/Glow_Item_Frame > Glow_Item_Frame.html
curl https://minecraft.fandom.com/wiki/Music_Disc > Music_Disc.html
curl https://minecraft.fandom.com/wiki/Painting > Painting.html
curl https://minecraft.fandom.com/wiki/Creative > Creative.html
curl https://minecraft.fandom.com/wiki/Spawn_Egg > Spawn_Egg.html
curl https://minecraft.fandom.com/wiki/Commands > Commands.html
curl https://minecraft.fandom.com/wiki/Minecart_with_Command_Block > Minecart_with_Command_Block.html
curl https://minecraft.fandom.com/wiki/Java_Edition > Java_Edition.html
curl https://minecraft.fandom.com/wiki/Bundle > Bundle.html
curl https://minecraft.fandom.com/wiki/Debug_Stick > Debug_Stick.html
curl https://minecraft.fandom.com/wiki/Knowledge_Book > Knowledge_Book.html
curl https://minecraft.fandom.com/wiki/Education_Edition > Education_Edition.html
curl https://minecraft.fandom.com/wiki/Camera > Camera.html
curl https://minecraft.fandom.com/wiki/Portfolio > Portfolio.html
curl https://minecraft.fandom.com/wiki/Photo > Photo.html
curl https://minecraft.fandom.com/wiki/Mundane_Potion > Mundane_Potion.html
curl https://minecraft.fandom.com/wiki/Thick_Potion > Thick_Potion.html
curl https://minecraft.fandom.com/wiki/Java_Edition > Java_Edition.html
curl https://minecraft.fandom.com/wiki/Potion_of_Luck > Potion_of_Luck.html
curl https://minecraft.fandom.com/wiki/Uncraftable_Potion > Uncraftable_Potion.html
curl https://minecraft.fandom.com/wiki/Bedrock_Edition > Bedrock_Edition.html
curl https://minecraft.fandom.com/wiki/Potion_of_Decay > Potion_of_Decay.html
curl https://minecraft.fandom.com/wiki/Potion#Unused_potions > Potion#Unused_potions.html
curl https://minecraft.fandom.com/wiki/Java_Edition_removed_features#Quiver > Java_Edition_removed_features#Quiver.html
curl https://minecraft.fandom.com/wiki/Emerald#History > Emerald#History.html
curl https://minecraft.fandom.com/wiki/Java_Edition > Java_Edition.html
curl https://minecraft.fandom.com/wiki/Crystallized_Honey > Crystallized_Honey.html
curl https://minecraft.fandom.com/wiki/Minecart_with_Dispenser > Minecart_with_Dispenser.html
curl https://minecraft.fandom.com/wiki/Java_Edition_removed_features#Studded_armor > Java_Edition_removed_features#Studded_armor.html
curl https://minecraft.fandom.com/wiki/Bedrock_Edition > Bedrock_Edition.html
curl https://minecraft.fandom.com/wiki/Minecart_with_Furnace > Minecart_with_Furnace.html
curl https://minecraft.fandom.com/wiki/Hoglin#Trivia > Hoglin#Trivia.html
curl https://minecraft.fandom.com/wiki/Java_Edition_15w14a > Java_Edition_15w14a.html
curl https://minecraft.fandom.com/wiki/Obsidian_Boat > Obsidian_Boat.html
curl https://minecraft.fandom.com/wiki/Java_Edition_1.RV-Pre1 > Java_Edition_1.RV-Pre1.html
curl https://minecraft.fandom.com/wiki/Smarter_Watch > Smarter_Watch.html
curl https://minecraft.fandom.com/wiki/Reality_Vision > Reality_Vision.html
curl https://minecraft.fandom.com/wiki/Ankle_Monitor > Ankle_Monitor.html
curl https://minecraft.fandom.com/wiki/Java_Edition_3D_Shareware_v1.34 > Java_Edition_3D_Shareware_v1.34.html
curl https://minecraft.fandom.com/wiki/3D > 3D.html
curl https://minecraft.fandom.com/wiki/Blue_Key > Blue_Key.html
curl https://minecraft.fandom.com/wiki/Red_Key > Red_Key.html
curl https://minecraft.fandom.com/wiki/Yellow_Key > Yellow_Key.html
curl https://minecraft.fandom.com/wiki/Java_Edition_20w14%E2%88%9E > Java_Edition_20w14%E2%88%9E.html
curl https://minecraft.fandom.com/wiki/Footprint > Footprint.html
curl https://minecraft.fandom.com/wiki/A_Very_Fine_Item > A_Very_Fine_Item.html
curl https://minecraft.fandom.com/wiki/Java_Edition > Java_Edition.html
curl https://minecraft.fandom.com/wiki/Java_Edition_removed_items#Potions > Java_Edition_removed_items#Potions.html
curl https://minecraft.fandom.com/wiki/Horse_Saddle > Horse_Saddle.html
curl https://minecraft.fandom.com/wiki/Java_Edition_removed_items#Reverted_potions > Java_Edition_removed_items#Reverted_potions.html
curl https://minecraft.fandom.com/wiki/Bedrock_Edition > Bedrock_Edition.html
curl https://minecraft.fandom.com/wiki/Camera > Camera.html
curl https://minecraft.fandom.com/wiki/Copper_Horn > Copper_Horn.html
curl https://minecraft.fandom.com/wiki/MinecraftEdu > MinecraftEdu.html
curl https://minecraft.fandom.com/wiki/Block_Inspector > Block_Inspector.html
npx prettier --write .